# Sample Normal Cell (NC)
num_cells:
  name : num_cells
  type : int
  value: 3
  low  : 1
  high : 3

# Normal Cells
normal_cells:
  name    : normal_cells
  type    : categorical
  choices :
            - Conv
            - DWConv
            - Bottleneck
            - InvertedResidualv2
            
# Reduction Cell
reduction_cells:
  name    : reduction_cells
  type    : categorical
  choices :
            - InvertedResidualv2
            - InvertedResidualv3
            - MaxPool
            - AvgPool

# Batch size
batch_size:
  name    : batch_size
  type    : categorical
  choices :
#             - 16
#             - 32
            - 64

# Epochs
epochs:
  name : epochs
  type : int
  low  : 3
  high : 3
  step : 10

# Optimizer parameter
optimizer:
  name    : optimizer
  type    : categorical
  choices : 
#             - SGD
#             - Adam
            - AdamW
            
# Scheduler parameter
scheduler:
  name    : scheduler
  type    : categorical
  choices : 
#             - StepLR
            - CosineAnnealingLR

# Criterion parameter
criterion:
  name    : criterion
  type    : categorical
  choices :
            - CrossEntropyLoss

# Input image size
img_size:
  name    : img_size
  type    : categorical
  choices :
            - 224

# Integer parameter - 
num_layers:
  name : num_layers
  type : int
  low  : 1
  high : 3

# Integer parameter (log)
num_channels:
  name : num_channels
  type : int
  low  : 32
  high : 52
  log  : True

# Integer parameter (discretized)
num_units:
  name : num_units
  type : int
  low  : 10
  high : 100
  step : 5

# Floating point parameter
dropout_rate:
  name : dropout_rate
  type : float
  low  : 0.2
  high : 0.2

# # Floating point parameter (log)
# learning_rate:
#   name : learning_rate
#   type : float
#   low  : 1e-5
#   high : 1e-1
#   log  : True

# Floating point parameter (log)
max_learning_rate:
  name : learning_rale
  type : float
  low  : 1e-5
  high : 1e-1
  log  : True

# Floating point parameter (discretized)
drop_path_rate:
  name : drop_path_rate
  type : float
  low  : 0.0
  high : 1.0
  step : 0.1

# Kernerl size parameter
kernel_size:
  name : kernel_size
  type : int
  low  : 1
  high : 5
