# optimizer config
Adam:
  lr     :
    name : lr
    type : float
    low  : 1e-5
    high : 1e-1
    log  : True

  betas  :
    name : betas
    type : float
    low  : 0.9
    high : 0.9
    beta2 : 0.9999

#   beta2  : #모르겠다. betas 어캐함;
#     name : beta2
#     type : float
#     low  : 0.9
#     high : 0.9999

AdamW:
  lr     : 
    name : lr
    type : float
    low  : 1e-5
    high : 1e-1
    log  : True
  
  betas  :
    name : betas
    type : float
    low  : 0.9
    high : 0.9
    beta2 : 0.9999

#   beta2  :
#     name : beta2
#     type : float
#     low  : 0.9
#     high : 0.9999

  weight_decay:
    name  : weight_decay
    type  : float
    low   : 0.0001
    high  : 0.01

SGD: 
  lr     :
    name : lr
    type : float
    low  : 1e-5
    high : 1e-1
    log  : True
