Adam:
  lr     : 
        name : learning_rate
        type : float
        low  : 1
        high : 3
  beta1  :
        name : beta1
        type : float
        low  : 0.8
        high : 0.95
  beta2  :
        name : beta2
        type : float
        low  : 0.9
        high : 0.9999

SGD: 
  lr     :
        name : learning_rate
        type : float
        
        ......
        